package ru.nsu.filters;

public enum FilterList {
    NEGATIVE,
    GRAYSCALE,
    GAMMA,
    ORDERED_DITHERING,
    FSDITHERING,
    GAUSSIAN_FILTER,
    SHARPENING,
    EMBOSS,
    SOBEL_HIGHLIGHTING,
    ROBERTS_HIGHLIGHTING,
    FSDITHERING_I,
    ORDERED_DITHER_I,
    CRYSTALLIZE,
    CYCLES,
    AQUA,
}
